[filters.get_link]
fn = "mknodes.jinja.filters.get_link"
group = "node"

[filters.get_link.examples.class]
template = """
{{ _mk.MkAdmonition | get_link }}
"""


[filters.get_url]
fn = "mknodes.jinja.filters.get_url"
group = "node"

[filters.get_url.examples.class]
template = """
{{ _mk.MkAdmonition | get_url }}
"""


[filters.link_for_class]
fn = "mknodes.jinja.filters.link_for_class"
group = "node"

[filters.link_for_class.examples.class]
template = """
{{ _mk.MkAdmonition | link_for_class }}
"""


[filters.link_for_module]
fn = "mknodes.jinja.filters.link_for_module"
group = "node"


[filters.to_html]
fn = "mknodes.jinja.filters.to_html"
group = "node"

[filters.to_html.examples.class]
template = """
{{ "test" | MkAdmonition | to_html }}
"""


[filters.apply_mod]
fn = "mknodes.jinja.filters.apply_mod"
group = "node"

[filters.apply_mod.examples.class]
template = """
{{ "test" | MkAdmonition | apply_mod("ParallaxEffect") }}
"""

[filters.add_annotation]
fn = "mknodes.jinja.filters.add_annotation"
group = "node"

[filters.add_annotation.examples.class]
template = """
{{ "test[1]" | MkAdmonition | add_annotation(1, "An annotation")) }}
"""


[filters.get_icon_svg]
fn = "mknodes.utils.icons.get_icon_svg"
group = "icon"

[filters.get_icon_svg.examples.class]
template = """
{{ "mdi:file" | get_icon_svg }}
"""


[filters.get_emoji_slug]
fn = "mknodes.utils.icons.get_emoji_slug"
group = "icon"

[filters.get_emoji_slug.examples.class]
template = """
{{ "mdi:file" | get_emoji_slug }}
"""


[filters.to_class]
fn = "mknodes.utils.classhelpers.to_class"
group = "node"

[filters.to_class.examples.class]
template = """
{{ "mknodes.MkAdmonition" | to_class }}
"""


[filters.url]
fn = "mknodes.jinja.filters.url"
group = "url"


[filters.script_tag]
fn = "mknodes.jinja.filters.script_tag"
group = "url"
