[metadata]
icon = "mdi:file-tree-outline"
name = "MkTreeView"

[examples.regular]
title = "Different styles"
jinja = """
{{ "src/mknodes/manual" | MkTreeView }}
"""

[examples.ansi]
title = "Style 'ansi'"
jinja = """
{{ "src/mknodes/manual" | MkTreeView(style="ansi") }}
"""

[examples.ascii]
title = "Style 'ascii'"
jinja = """
{{ "src/mknodes/manual" | MkTreeView(style="ascii") }}
"""

[examples.rounded]
title = "Style 'rounded'"
jinja = """
{{ "src/mknodes/manual" | MkTreeView(style="rounded") }}
"""

[examples.spaces]
title = "Style 'spaces'"
jinja = """
{{ "src/mknodes/manual" | MkTreeView(style="spaces") }}
"""

# [examples.remote]
# title = "Files from a repote path"
# jinja = """
# {{ "github://" | MkTreeView(storage_options={"org": "mkdocstrings", "repo": "mkocstrings"}, maximum_depth=2) }}
# """
