[metadata]
icon = "mdi:text"
name = "MkText"

[examples.regular]
title = "Regular"
jinja = """
{{ "Some text" | MkText }}
"""

[examples.from_url]
title = "From URL"
jinja = """
{{ mk.MkText.from_url("https://raw.githubusercontent.com/phil65/mknodes/main/README.md") }}
"""
