[metadata]
icon = "mdi:text"

[examples.regular]
title = "Regular"
jinja = """
{{ "Some text" | MkText | MkReprRawRendered }}
"""

[examples.from_url]
title = "From URL"
jinja = """
{{ _mk.MkText.from_url("https://raw.githubusercontent.com/phil65/mknodes/main/README.md") | MkReprRawRendered }}
"""
